# Configuration for GitHub's automatic release notes
changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
  categories:
    - title: Breaking Changes
      labels:
        - "breaking change"
    - title: Features
      labels:
        - "Type/New Feature"
    - title: Improvements
      labels:
        - "Type/Improvement"
    - title: Bug Fixes
      labels:
        - "Type/Bug"
    - title: Other Changes
      labels:
        - "*"