packages:
  - "backend"
  - "frontend"
  - "docs"

allowBuilds:
  core-js: false
  msw: false
  sharp: false
  unrs-resolver: false
  "@scarf/scarf": true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  '@google/genai': true
  '@swc/core': false
