import { describe, it, expect, afterEach } from "vitest";
import { cleanup, render, screen, within } from "@testing-library/react";
import { CandidateAiAnalysis } from "@/app/(dashboard)/candidates/[id]/_components/candidate-ai-analysis";
import { AiAnalysisSection } from "@/app/(dashboard)/candidates/[id]/_components/sections/ai-analysis-section";
import type { CandidateCvAnalysisPayload } from "@/types";

const analysis = (over: Partial<CandidateCvAnalysisPayload> = {}): CandidateCvAnalysisPayload => ({
  status: "done",
  matchedSkills: ["Typescript", "React", "PostgreSQL"],
  missingSkills: ["Go"],
  aiSummary: {
    quickSummary: "An intern with a full-stack foundation.",
    strengths: ["Direct match for TypeScript.", "Certified in WSO2."],
    gaps: ["No professional experience with Go."],
  },
  errorMessage: null,
  updatedAt: "2026-09-09T10:00:00Z",
  ...over,
});

const renderNotes = (cv: CandidateCvAnalysisPayload | null, resumeUrl: string | null = "https://x/cv.pdf") =>
  render(<CandidateAiAnalysis resumeUrl={resumeUrl} cv={cv} />);

afterEach(cleanup);

describe("CandidateAiAnalysis", () => {
  it("shows the summary, strengths and gaps as notes", () => {
    renderNotes(analysis());
    expect(screen.getByText(/An intern with a full-stack foundation/)).toBeTruthy();
    expect(screen.getByText("Direct match for TypeScript.")).toBeTruthy();
    expect(screen.getByText("No professional experience with Go.")).toBeTruthy();
  });

  it("shows no score, no progress bar and no verdict", () => {
    // Data shaped like an analysis saved before the score and verdict were removed.
    const old = {
      ...analysis(),
      matchScore: "12.00",
      scoreBreakdown: { skills: 5, experience: 2, level: 3, certs: 2 },
      aiSummary: {
        ...analysis().aiSummary!,
        verdict: "not_recommended",
        hiringSignal: "Do not interview.",
      },
    } as unknown as CandidateCvAnalysisPayload;
    renderNotes(old);

    expect(screen.queryByRole("progressbar")).toBeNull();
    expect(screen.queryByText(/\/ ?100/)).toBeNull();
    expect(screen.queryByText("12")).toBeNull();
    for (const verdict of ["Not recommended", "Strong fit", "Moderate fit", "Weak fit"]) {
      expect(screen.queryByText(verdict)).toBeNull();
    }
    expect(screen.queryByText("Do not interview.")).toBeNull();
    expect(screen.queryByText(/Hiring signal/i)).toBeNull();
    expect(screen.queryByText(/breaks down/i)).toBeNull();
  });

  it("lists which of the job's skills the CV shows, without calling the rest 'missing'", () => {
    renderNotes(analysis());
    const skills = screen.getByRole("heading", { name: "Skills this job asks for" }).closest("section")!;
    expect(within(skills).getByText("Found in the CV (3)")).toBeTruthy();
    expect(within(skills).getByText("Not found in the CV (1)")).toBeTruthy();
    expect(within(skills).getByText("Go")).toBeTruthy();
  });

  it("has no button or dialog: everything is on the page", () => {
    renderNotes(analysis());
    expect(screen.queryByRole("button")).toBeNull();
    expect(screen.queryByRole("dialog")).toBeNull();
  });

  it("reminds the reader the notes can be wrong", () => {
    renderNotes(analysis());
    expect(screen.getByText(/Read the CV yourself before you decide/)).toBeTruthy();
  });

  it("still shows the skills when the written summary could not be made", () => {
    renderNotes(analysis({ aiSummary: null }));
    expect(screen.getByText("Found in the CV (3)")).toBeTruthy();
    expect(screen.queryByRole("heading", { name: "Summary" })).toBeNull();
  });

  it("says so when the AI had nothing to note", () => {
    renderNotes(analysis({ aiSummary: null, matchedSkills: [], missingSkills: null }));
    expect(screen.getByText(/had nothing to note/)).toBeTruthy();
  });

  it("explains each state that has no notes yet", () => {
    renderNotes(null, null);
    expect(screen.getByText(/No CV on file/)).toBeTruthy();
    cleanup();

    renderNotes(null);
    expect(screen.getByText(/There is no AI analysis for this candidate/)).toBeTruthy();
    cleanup();

    renderNotes(analysis({ status: "pending" }));
    expect(screen.getByText("Reading the CV")).toBeTruthy();
    cleanup();

    renderNotes(analysis({ status: "failed", errorMessage: "Not a CV." }));
    expect(screen.getByRole("alert").textContent).toMatch(/Not a CV\./);
  });
});

describe("AiAnalysisSection", () => {
  it("is titled AI analysis and says it is not part of the score", () => {
    render(<AiAnalysisSection resumeUrl={null} cvAnalysis={null} />);
    expect(screen.getByRole("heading", { name: "AI analysis" })).toBeTruthy();
    expect(screen.getByText("Generated by AI. Not part of the score.")).toBeTruthy();
  });
});
