"use client";

import { CandidateAiAnalysis } from "@/components/dynamic-imports";
import type { CandidateCvAnalysisPayload } from "@/types";

/** Shown only while AI CV analysis is turned on in Settings. */
export function AiAnalysisSection({
  resumeUrl,
  cvAnalysis,
}: {
  resumeUrl: string | null;
  cvAnalysis: CandidateCvAnalysisPayload | null;
}) {
  return (
    <div className="p-5 sm:p-6">
      <div className="mb-6">
        <h3 className="text-sm font-bold text-slate-900 dark:text-neutral-100">
          AI analysis
        </h3>
        <p className="text-sm text-slate-500 dark:text-neutral-400 mt-0.5">
          Generated by AI. Not part of the score.
        </p>
      </div>
      <CandidateAiAnalysis resumeUrl={resumeUrl} cv={cvAnalysis} />
    </div>
  );
}
