<<<<<<< HEAD
name: Deploy Backend
=======
name: Deploy backend
>>>>>>> 5aa54e9b9a1cf1be9628ddae71127d571cfd09b1

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
<<<<<<< HEAD
        uses: actions/checkout@v4

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
=======
        uses: actions/checkout@v4.2.2

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.2.2
>>>>>>> 5aa54e9b9a1cf1be9628ddae71127d571cfd09b1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
<<<<<<< HEAD
=======
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
>>>>>>> 5aa54e9b9a1cf1be9628ddae71127d571cfd09b1
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm build
            pm2 restart openats-backend
            pm2 save
